name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Build and Test AssertYourself
      run: xcodebuild clean build test -project 01.AssertYourself/AssertYourself.xcodeproj -scheme "AssertYourself" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES

    - name: Build and Test LifeCycle
      run: xcodebuild clean build test -project 02.LifeCycle/LifeCycle.xcodeproj -scheme "LifeCycle" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES

    - name: Build and Test CodeCoverage
      run: xcodebuild clean build test -project 03.CodeCoverage/CodeCoverage.xcodeproj -scheme "CodeCoverage" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES
      
    - name: Build and Test AppLaunch
      run: xcodebuild clean build test -project 04.AppLaunch/AppLaunch.xcodeproj -scheme "AppLaunch" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES

    - name: Build and Test LoadViewControllers
      run: xcodebuild clean build test -project 05.LoadViewControllers/LoadViewControllers.xcodeproj -scheme "LoadViewControllers" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES

    - name: Build and Test HardDependencies
      run: xcodebuild clean build test -project 06.HardDependencies/HardDependencies.xcodeproj -scheme "HardDependencies" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES

    - name: Build and Test OutletConnections
      run: xcodebuild clean build test -project 07.OutletConnections/OutletConnections.xcodeproj -scheme "OutletConnections" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES

    - name: Build and Test ButtonTap
      run: xcodebuild clean build test -project 08.ButtonTap/ButtonTap.xcodeproj -scheme "ButtonTap" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES

    - name: Build and Test Alert
      run: xcodebuild clean build test -project 09.Alert/Alert.xcodeproj -scheme "Alert" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES

    - name: Build and Test Navigation
      run: xcodebuild clean build test -project 10.Navigation/Navigation.xcodeproj -scheme "Navigation" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES

    - name: Build and Test UserDefaults
      run: xcodebuild clean build test -project 11.UserDefaults/UserDefaults.xcodeproj -scheme "UserDefaults" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES

    - name: Build and Test NetworkRequest
      run: xcodebuild clean build test -project 12.NetworkRequest/NetworkRequest.xcodeproj -scheme "NetworkRequest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES
