name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app

    - name: Build and test
    
      run: xcodebuild clean test -project 01.AssertYourself/AssertYourself.xcodeproj -scheme "AssertYourself" -destination "name=iPhone X,OS=12.1" 
      
      
      
      
